// Code generated by mockery v1.0.0
package mocks

import core "github.com/sc2nomore/tic-tac-go/core"
import mock "github.com/stretchr/testify/mock"

// BoardRender is an autogenerated mock type for the BoardRender type
type BoardRender struct {
	mock.Mock
}

// RenderBoard provides a mock function with given fields: board, players
func (_m *BoardRender) RenderBoard(board core.Board, players core.PlayerMapper) string {
	ret := _m.Called(board, players)

	var r0 string
	if rf, ok := ret.Get(0).(func(core.Board, core.PlayerMapper) string); ok {
		r0 = rf(board, players)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
