// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Console is an autogenerated mock type for the Console type
type Console struct {
	mock.Mock
}

// ClearConsole provides a mock function with given fields:
func (_m *Console) ClearConsole() {
	_m.Called()
}

// ReadInput provides a mock function with given fields:
func (_m *Console) ReadInput() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RenderMessage provides a mock function with given fields: str
func (_m *Console) RenderMessage(str string) {
	_m.Called(str)
}
