// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Player is an autogenerated mock type for the Player type
type Player struct {
	mock.Mock
}

// Move provides a mock function with given fields:
func (_m *Player) Move() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Symbol provides a mock function with given fields:
func (_m *Player) Symbol() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
