// Code generated by mockery v1.0.0
package mocks

import boards "github.com/sc2nomore/tic-tac-go/core/boards"
import mock "github.com/stretchr/testify/mock"

// Rules is an autogenerated mock type for the Rules type
type Rules struct {
	mock.Mock
}

// IsTie provides a mock function with given fields: board
func (_m *Rules) IsTie(board boards.Playable) bool {
	ret := _m.Called(board)

	var r0 bool
	if rf, ok := ret.Get(0).(func(boards.Playable) bool); ok {
		r0 = rf(board)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsWin provides a mock function with given fields: board, player
func (_m *Rules) IsWin(board boards.Playable, player int) bool {
	ret := _m.Called(board, player)

	var r0 bool
	if rf, ok := ret.Get(0).(func(boards.Playable, int) bool); ok {
		r0 = rf(board, player)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
