// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Styler is an autogenerated mock type for the Styler type
type Styler struct {
	mock.Mock
}

// Style provides a mock function with given fields: square, squareIndex, marker
func (_m *Styler) Style(square int, squareIndex int, marker string) string {
	ret := _m.Called(square, squareIndex, marker)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, int, string) string); ok {
		r0 = rf(square, squareIndex, marker)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
