// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// UI is an autogenerated mock type for the UI type
type UI struct {
	mock.Mock
}

// GetMove provides a mock function with given fields:
func (_m *UI) GetMove() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RenderBoard provides a mock function with given fields:
func (_m *UI) RenderBoard() {
	_m.Called()
}
