// Code generated by mockery v1.0.0
package mocks

import boards "github.com/sc2nomore/tic-tac-go/core/boards"
import core "github.com/sc2nomore/tic-tac-go/core"
import mock "github.com/stretchr/testify/mock"

// BoardRender is an autogenerated mock type for the BoardRender type
type BoardRender struct {
	mock.Mock
}

// RenderBoard provides a mock function with given fields: board, players
func (_m *BoardRender) RenderBoard(board boards.Board, players core.PlayerMap) {
	_m.Called(board, players)
}
